Added support for opensearch configuration on log_destination block
digitalocean/terraform-provider-digitalocean pull request #1200
Opened 2024-08-21 15:27 UTC by GiovanniColonni

2024-08-21 17:07 UTC, danaelhe commented
#1175

2024-08-21 17:44 UTC, GiovanniColonni commented
I see the PR for the documentation but the block for defining the destination is still not available to use in DO with terraform

2024-08-21 17:52 UTC, danaelhe commented
> I see the PR for the documentation but the block for defining the destination is still not available to use in DO with terraform

Yes, you're right! Usually we include documentation in the same PR as the implemmentation. Could you add that in this PR if possible? Thank you SO much for your contribution!

2024-08-21 20:59 UTC, danaelhe commented
> I only see [this file ](https://github.com/digitalocean/terraform-provider-digitalocean/pull/1198/files) but it's already merged so maybe I don't understand the request

Oh apologies- you're good then. The documentation you have in this PR already will suffice.

2024-08-21 21:05 UTC, danaelhe commented on digitalocean/app/app_spec.go
> +	"net/http"
```suggestion
	"log"
	"net/http"

	"github.com/digitalocean/godo"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
```

^^ should fix lint ci issue!

2024-08-23 18:53 UTC, danaelhe requested changes
Looks great!! Added a few changes. Tested locally and seems to work well:

```
resource "digitalocean_app" "golang-sample" {
  spec {
    name   = "golang-sample"
    region = "ams"

    service {
      name               = "go-service"
      environment_slug   = "go"
      instance_count     = 1
      instance_size_slug = "professional-xs"

      git {
        repo_clone_url = "https://github.com/digitalocean/sample-golang.git"
        branch         = "main"
      }

      log_destination {
        name = "MyLogs"
        open_search {
          endpoint = "https://something:1234"
          basic_auth {
            user = "user"
            password = "hi"
          }
        }
      }
    }
  }
}
```

2024-08-23 18:53 UTC, danaelhe commented on digitalocean/app/app_spec.go
> +		}
```suggestion
		if len(open_search) > 0 {
			openSearchConfig := open_search[0].(map[string]interface{})
			d.OpenSearch = &godo.AppLogDestinationSpecOpenSearch{
				Endpoint:    (openSearchConfig["endpoint"].(string)),
				BasicAuth:   expandAppOpensearchBasicAuth(openSearchConfig["basic_auth"].([]interface{})),
				IndexName:   (openSearchConfig["index_name"].(string)),
				ClusterName: (openSearchConfig["cluster_name"].(string)),
			}
		}
```
The API will do these checks for us :)

2024-08-23 18:53 UTC, danaelhe commented on digitalocean/app/app_spec.go
> +										Required:    true,
```suggestion
										Optional:    true,
```
This is also optional:

> Username to authenticate with. Only required when endpoint is set. Defaults to doadmin when cluster_name is set.

2024-08-23 18:53 UTC, danaelhe commented on digitalocean/app/app_spec.go
> +		}
```suggestion
		if d.OpenSearch != nil {
			openSearch := make([]interface{}, 1)

			openSearch[0] = map[string]interface{}{
				"endpoint":     d.OpenSearch.Endpoint,
				"cluster_name": d.OpenSearch.ClusterName,
				"index_name":   d.OpenSearch.IndexName,
				"basic_auth": []interface{}{
					map[string]string{
						"user":     d.OpenSearch.BasicAuth.User,
						"password": d.OpenSearch.BasicAuth.Password,
					},
				},
			}

			r["open_search"] = openSearch
		}
```
The API will perform these checks for us :)

2024-08-23 18:53 UTC, danaelhe commented on digitalocean/app/app_spec.go
> +		}
Also included this function 🤖 
```
func expandAppOpensearchBasicAuth(config []interface{}) *godo.OpenSearchBasicAuth {
	basicAuthConfig := config[0].(map[string]interface{})

	basicAuth := &godo.OpenSearchBasicAuth{
		User:     string(basicAuthConfig["user"].(string)),
		Password: string(basicAuthConfig["password"].(string)),
	}

	return basicAuth
}
```

2024-08-26 09:00 UTC, GiovanniColonni reviewed
looks like all good at this point, thanks for helping

2024-08-26 14:28 UTC, danaelhe approved these changes
Looks great! Thank you so much for your contribution and help 🫶 

Added an example in docs in last commit to address #1175

2024-08-26 14:28 UTC, merged