Update Terraform provider to include new opensearch acl changes
digitalocean/terraform-provider-digitalocean pull request #1215
Opened 2024-09-20 10:29 UTC by bhardwajRahul

This PR aims at adding support for opensearch acl changes to DO's Terraform Provider.

2024-09-20 13:49 UTC, loosla commented
Looks good to me :rocket: :rocket: :rocket: 

Just a small question (nothing critical, just curiosity):
Do you think that `normalizeOpenSearchPermission` is reachable with this configuration 
```
                      "permission": {
				Type:     schema.TypeString,
				Required: true,
				ValidateFunc: validation.StringInSlice([]string{
					"deny",
					"admin",
					"read",
					"write",
					"readwrite",
				}, false),
			},
```
It looks like anything that is not in a list of allowed values will be denied before we get to normalisation.
So, `read_write` will be denied as well as uppercase values like `READ`.
Normalisation still can make sense if _validation_ will be changed in the future though. :thinking:

2024-09-20 15:22 UTC, bhardwajRahul commented
> Looks good to me 🚀 🚀 🚀
> 
> Just a small question (nothing critical, just curiosity): Do you think that `normalizeOpenSearchPermission` is reachable with this configuration
> 
> ```
>                       "permission": {
> 				Type:     schema.TypeString,
> 				Required: true,
> 				ValidateFunc: validation.StringInSlice([]string{
> 					"deny",
> 					"admin",
> 					"read",
> 					"write",
> 					"readwrite",
> 				}, false),
> 			},
> ```
> 
> It looks like anything that is not in a list of allowed values will be denied before we get to normalisation. So, `read_write` will be denied as well as uppercase values like `READ`. Normalisation still can make sense if _validation_ will be changed in the future though. 🤔

@loosla yes, this has been added for the pupose of validation and we are using similar pattern for kafka acls also.

2024-09-24 14:34 UTC, andrewsomething commented on digitalocean/database/resource_database_user_test.go
> +  engine     = "openserach"
```suggestion
  engine     = "opensearch"
```

```
=== CONT  TestAccDigitalOceanDatabaseUser_OpenSearchACLs
    resource_database_user_test.go:267: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating database cluster: POST https://api.digitalocean.com/v2/databases: 422 (request "f05bf517-5041-4a70-b64a-a80330bcb550") invalid engine
        
          with digitalocean_database_cluster.foobar,
          on terraform_plugin_test.tf line 2, in resource "digitalocean_database_cluster" "foobar":
           2: resource "digitalocean_database_cluster" "foobar" {
        
--- FAIL: TestAccDigitalOceanDatabaseUser_OpenSearchACLs (2.70s)
```

2024-09-24 14:35 UTC, andrewsomething requested changes
Looks like a typo in the acceptance test config is causing a failure.

2024-09-24 17:49 UTC, loosla approved these changes
:+1:

2024-09-24 18:00 UTC, andrewsomething requested changes

2024-09-24 18:00 UTC, andrewsomething commented on digitalocean/database/resource_database_user_test.go
> +  size       = "db-s-2vcpu-2gb"
This doesn't seem to be a valid size for an OpenSearch cluster:

```
        Error: Error creating database cluster: POST https://api.digitalocean.com/v2/databases: 422 (request "822ac77c-4ce2-489f-9d3d-838e22475d6a") invalid size
        
          with digitalocean_database_cluster.foobar,
          on terraform_plugin_test.tf line 2, in resource "digitalocean_database_cluster" "foobar":
           2: resource "digitalocean_database_cluster" "foobar" {
```

Can you please ensure your new acceptance test passes. You can run just your test with:

```
make testacc TESTARGS='-run=TestAccDigitalOceanDatabaseUser_OpenSearchACLs'
```

2024-09-25 10:30 UTC, bhardwajRahul commented
![image](https://github.com/user-attachments/assets/e401e4ea-b8c1-4c20-99e6-f7291464d78f)

2024-09-25 16:49 UTC, andrewsomething approved these changes
:+1:  Thanks for fixing up the acceptance test! LGTM!

2024-09-25 16:52 UTC, merged