Feature: digitalocean_image
digitalocean/terraform-provider-digitalocean pull request #517
Opened 2020-11-09 05:40 UTC by frezbo

Signed-off-by: Noel Georgi <git@frezbo.com>

Fixes #160

Good to Have:

- The `Update` operation currently only updates the name since the `godo` client only supports that at the moment
- Copying to multiple regions is not supported yet

2020-11-09 05:44 UTC, frezbo commented
Output of acceptance test:

```bash
❯ TF_ACC=1 DIGITALOCEAN_TOKEN="<redacted>" go test github.com/digitalocean/terraform-provider-digitalocean/digitalocean -run ^TestAccDigitalOceanImageFull$
ok      github.com/digitalocean/terraform-provider-digitalocean/digitalocean    (cached)
```

2020-11-09 17:06 UTC, andrewsomething requested changes
@frezbo, this looks great! I've left a few small comments in-line. 

Also, it would be great to get some docs for this. You can look at one of the existing pages for an exmaple: https://github.com/digitalocean/terraform-provider-digitalocean/blob/master/docs/resources/droplet_snapshot.md

2020-11-09 17:06 UTC, andrewsomething commented on digitalocean/resource_digitalocean_image.go
> +func resourceDigitalOceanImage() *schema.Resource {
```suggestion
func resourceDigitalOceanCustomImage() *schema.Resource {
```

The methods names as well.

2020-11-10 17:41 UTC, frezbo commented on digitalocean/provider.go
> +			"digitalocean_image":                                 resourceDigitalOceanImage(),
sure, I could make this change. `digitalocean_custom_image` makes more sense

2020-11-12 19:37 UTC, frezbo commented on digitalocean/resource_digitalocean_image_test.go
> +	rString := acctest.RandString(5)
resolved

2020-11-12 19:37 UTC, frezbo commented on digitalocean/provider.go
> +			"digitalocean_image":                                 resourceDigitalOceanImage(),
resolved

2020-11-12 19:37 UTC, frezbo commented on digitalocean/resource_digitalocean_image.go
> +				ValidateFunc: validation.NoZeroValues,
resolved

2020-11-12 19:37 UTC, frezbo commented on digitalocean/resource_digitalocean_image.go
> +func resourceDigitalOceanImage() *schema.Resource {
resolved

2020-11-12 19:38 UTC, frezbo commented
Output of acceptance test after the changes:

```bash
❯ TF_ACC=1 DIGITALOCEAN_TOKEN="<redacted>" go test github.com/digitalocean/terraform-provider-digitalocean/digitalocean -run ^TestAccDigitalOceanCustomImageFull$
ok      github.com/digitalocean/terraform-provider-digitalocean/digitalocean    290.440s
```

2020-11-12 22:10 UTC, andrewsomething approved these changes
:+1:  Looks great. Thanks for the contribution!

2020-11-12 22:10 UTC, merged

2020-11-17 19:42 UTC, paulo-digital commented
Nice feature introduction, it was missing. Although some important properties are missing here, the most notable are `size` and `user_data`, for a custom image those are a SHOULD HAVE property. Is unusable for my use cases, I hope to see those implemented in the future. Thank you, nice job.

2020-11-17 19:56 UTC, andrewsomething commented
Hi @paulo-digital,

This resource just creates a custom image that can be used to create Droplets. You would need to specify the `size` and `user_data` when you create the Droplet, e.g:

```
resource "digitalocean_custom_image" "focal" {
  name         = "ubuntu-20.04-minimal-cloudimg-amd64"
  distribution = "Ubuntu"
  description  = "testing..."
  url          = "https://cloud-images.ubuntu.com/minimal/releases/focal/release/ubuntu-20.04-minimal-cloudimg-amd64.img"
  regions      = ["nyc3"]
}

resource "digitalocean_droplet" "example" {
  image     = digitalocean_custom_image.focal.id
  name      = "example-1"
  region    = "nyc3"
  size      = "s-1vcpu-1gb"
  user_data = "my script here..."
  ssh_keys  = [123456]
}
```

2020-11-17 20:01 UTC, paulo-digital commented
Nice feature introduction, it was missing. But how to proper implement it? I tried something like below with no success. Can you lead me to a more complete documentation?   Thank you.

Declare:
```
resource "digitalocean_custom_image" "flatcar" {
  name   = "flatcar"
  url = "https://stable.release.flatcar-linux.net/amd64-usr/2605.7.0/flatcar_production_digitalocean_image.bin.bz2"
  regions = ["nyc3"]
}
```

Use?!:

```
resource "digitalocean_droplet" "quickstart_node" {
  name               = "${var.prefix}-quickstart-node"
  image              = digitalocean_custom_image.flatcar.name   
  region             = var.do_region
  size               = var.droplet_size`
}
```

2020-11-17 21:06 UTC, paulo-digital commented
> Hi @paulo-digital,
> 
> This resource just creates a custom image that can be used to create Droplets. You would need to specify the `size` and `user_data` when you create the Droplet, e.g:
> 
> ```
> resource "digitalocean_custom_image" "focal" {
>   name         = "ubuntu-20.04-minimal-cloudimg-amd64"
>   distribution = "Ubuntu"
>   description  = "testing..."
>   url          = "https://cloud-images.ubuntu.com/minimal/releases/focal/release/ubuntu-20.04-minimal-cloudimg-amd64.img"
>   regions      = ["nyc3"]
> }
> 
> resource "digitalocean_droplet" "example" {
>   image     = digitalocean_custom_image.focal.id
>   name      = "example-1"
>   region    = "nyc3"
>   size      = "s-1vcpu-1gb"
>   user_data = "my script here..."
>   ssh_keys  = [123456]
> }
> ```

Fantastic, that's what I was trying to figure out!! Thank you.