App: internal ports array attribute
digitalocean/terraform-provider-digitalocean pull request #570
Opened 2021-02-01 18:38 UTC by rienafairefr

The digitalocean_app spec was also missing the internal_ports attribute on a service, this should fix this. Acceptance test (`TestAccDigitalOceanApp_InternalPort`) is passing
internal_ports are specified like `internal_ports = ["5000"]`, maybe an array syntax
```
internal_port {
   port = 5000
}
internal_port {
   port = 2000
}
```
would be preferred, similarly to the routes attribute. not sure.

2021-02-01 18:57 UTC, andrewsomething commented
> passing internal_ports are specified like internal_ports = ["5000"], maybe an array syntax

I think you've got it right as it currently is. I matches how the yaml spec spec treats them:

```
  internal_ports:
  - 5000
  - 3000
  routes:
  - path: /
  - path: /foo
```

https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/

`routes` could grow additional attributes while `internal_ports` will always be a list of integers.

2021-02-01 19:00 UTC, andrewsomething requested changes
Looks great. I left one comment in line. Think we can get rid of `appSpecInternalPortSchema()`

2021-02-01 19:00 UTC, andrewsomething commented on digitalocean/app_spec.go
> +func appSpecInternalPortSchema() *schema.Resource {
Looks like this is not used?

2021-02-03 16:32 UTC, andrewsomething commented on digitalocean/app_spec.go
> +func appSpecInternalPortSchema() *schema.Resource {
I've pushed a commit removing this.

2021-02-03 16:33 UTC, andrewsomething approved these changes
:shipit: Thanks again for the great contributions!

2021-02-03 16:33 UTC, merged

2021-02-03 17:00 UTC, rienafairefr commented on digitalocean/app_spec.go
> +func appSpecInternalPortSchema() *schema.Resource {
Thanks!